#!/usr/bin/env python
# coding: utf-8

# In[5]:


# Copyright (c) 2026 Hiroshi Harada
# Licensed under the MIT License.
# https://opensource.org/licenses/MIT

"""
6-adic Prime Chain Discovery Script (Jupyter-friendly version)
Author: Hiroshi Harada
Date: February 2026
License: MIT

This script performs a single-threaded search for prime chains generated by the 6-adic mapping:

    f(n) = (7n ± k) / 6, where k ∈ {1, 5}

The constant k is selected based on n mod 12 to ensure the result is an odd integer.
This parity-preserving logic avoids even-number traps and supports geometric growth.

Dependencies:
- Python 3.6+
- sympy

To install dependencies:
    pip install sympy
"""

from sympy import isprime
import time

def get_next_6adic_custom(n):
    """
    Computes the next value in the 6-adic sequence.
    The constant k is selected based on n mod 12 to ensure (7n ± k) is divisible by 6 and the result is odd.
    """
    rem = n % 12
    if rem == 1:
        return (7 * n - 1) // 6
    elif rem == 5:
        return (7 * n - 5) // 6
    elif rem == 7:
        return (7 * n + 5) // 6
    elif rem == 11:
        return (7 * n + 1) // 6
    return None  # Invalid case

def check_range_6adic(start, end, verbose=True):
    """
    Searches for prime chains within the given range [start, end).
    Only odd starting values are considered.
    Returns a list of tuples: (chain length, chain list)
    """
    results = []
    for n0 in range(start | 1, end, 2):  # Skip even numbers
        if not isprime(n0):
            continue

        chain = []
        history = set()
        curr = n0

        while curr not in history:
            if not isprime(curr):
                break
            chain.append(curr)
            history.add(curr)

            nxt = get_next_6adic_custom(curr)
            if nxt is None or nxt % 2 == 0:
                break
            curr = nxt

        if len(chain) >= 7:
            results.append((len(chain), chain))
            if verbose:
                print(f"[!] Hit! L{len(chain)} at n₀ = {chain[0]}")
                for p in chain:
                    print(f"      {p}")
    return results

def run_6adic_search(upper_limit=100_000):
    """
    Runs a single-threaded search for 6-adic prime chains up to upper_limit.
    Suitable for Jupyter or limited environments.
    """
    print(f"--- 6-adic Prime Chain Hunt (Single-threaded) ---")
    print(f"[*] Logic: (7n ± 1,5) / 6")
    print(f"[*] Range: 3 to {upper_limit:,}")

    start_time = time.time()
    results = check_range_6adic(3, upper_limit)
    elapsed = time.time() - start_time

    print(f"\n--- Hunt Complete ({elapsed:.2f} seconds) ---")
    print(f"Total L7+ chains discovered: {len(results)}")
    return results

# run_6adic_search(100000)
run_6adic_search(10_000_000)


# In[ ]:




